#CI项目
name: OWRT-ALL

#CI计划
on:
  #自动编译：当Auto-Clean运行完成后
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  #手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: false
        required: false
        type: boolean
      VERBOSE:
        description: '编译日志级别: 99/debug(最详细), sc/commands(显示命令), s/silent(静默), 1/basic(基本), 0/quiet(最少)'
        default: 's'
        required: false
        type: string
      THREADS:
        description: '编译线程数 (0表示自动检测CPU核心数)'
        default: '0'
        required: false
        type: string

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        CONFIG: [X86]
        SOURCE: [immortalwrt/immortalwrt]
        BRANCH: [master]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: OpenWRT
      #默认WIFI名称
      WRT_SSID: OpenWRT
      #默认WIFI密码
      WRT_WORD: asd12345A
      #默认地址
      WRT_IP: 10.0.0.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
      #编译日志级别
      WRT_VERBOSE: ${{inputs.VERBOSE || 's'}}
      #编译线程数
      WRT_THREADS: ${{inputs.THREADS || '0'}}
